import { useForm } from 'react-hook-form';
import api from '../../api/axios';
import { useState } from 'react';

const CreateClient = () => {
    const { register, handleSubmit, reset, formState: { errors } } = useForm();
    const [msg, setMsg] = useState(null);
    const [isError, setIsError] = useState(false);

    const onSubmit = async (data) => {
        setMsg(null);
        setIsError(false);
        try {
            await api.post('/clients', data);
            setMsg('Client créé avec succès. Un email a été envoyé.');
            reset();
        } catch (err) {
            setIsError(true);
            setMsg('Erreur: ' + (err.response?.data?.error || err.message));
        }
    };

    return (
        <div className="form-page">
            <h2 className="page-title">Créer un Nouveau Client</h2>
            <form onSubmit={handleSubmit(onSubmit)} className="card form-card">
                {msg && <div className={isError ? "error-banner" : "success-banner"}>{msg}</div>}

                <div className="form-row">
                    <div className="form-group">
                        <label>Login</label>
                        <input {...register('login', { required: true })} className="input-field" />
                        {errors.login && <span className="error-text">Requis</span>}
                    </div>
                    {/* Password generated by backend */}
                    <div className="form-group">
                        <label>Email</label>
                        <input type="email" {...register('email', { required: true })} className="input-field" />
                        {errors.email && <span className="error-text">Requis</span>}
                    </div>
                </div>

                <div className="form-row">
                    <div className="form-group">
                        <label>Nom</label>
                        <input {...register('nom', { required: true })} className="input-field" />
                    </div>
                    <div className="form-group">
                        <label>Prénom</label>
                        <input {...register('prenom', { required: true })} className="input-field" />
                    </div>
                </div>

                <div className="form-group">
                    <label>Numéro Identité (CIN)</label>
                    <input {...register('identiteNum', { required: true })} className="input-field" />
                </div>

                <div className="form-group">
                    <label>Date de Naissance</label>
                    <input type="date" {...register('dateNaissance', { required: true })} className="input-field" />
                </div>

                <div className="form-group">
                    <label>Adresse Postale</label>
                    <textarea {...register('adressePostale', { required: true })} className="input-field" />
                </div>

                <button type="submit" className="btn-primary">Créer Client</button>
            </form>
        </div>
    );
};

export default CreateClient;
